#pragma once

/**
 * @file DeviceAuth.h
 * @brief Per-device JWT authentication helper for the ESP32 FOTA client.
 */

/*
 * DeviceAuth.h - Per-device authentication helper for the FOTA ESP32 library
 *
 * Handles the full device credential lifecycle:
 *   1. Store device_id + device_secret in ESP32 NVS (Preferences).
 *   2. POST /api/v1/devices/authenticate → receive a 30-day JWT.
 *   3. Cache the JWT in NVS so it survives reboots.
 *   4. Transparently re-authenticate when the cached token is expired.
 *   5. Inject the token into FotaClient via applyTo().
 *
 * Quick start:
 *   DeviceAuth auth;
 *   auth.setServerUrl("https://api.example.com");
 *   auth.setDeviceId("esp32-serial-abc123");
 *   auth.setDeviceSecret("64-hex-char-secret-from-dashboard");
 *   if (auth.ensureValid()) {
 *     auth.applyTo(fota);   // sets FotaClient auth token
 *   }
 *
 * Compile-time defaults (override with #define before including this header):
 *   DEVICE_AUTH_SERVER_URL    — backend base URL
 *   DEVICE_AUTH_DEVICE_ID     — device business key
 *   DEVICE_AUTH_DEVICE_SECRET — raw 64-hex-char secret
 *   DEVICE_AUTH_API_PREFIX    — API path prefix (default: "/api/v1")
 *   DEVICE_AUTH_NVS_NS        — NVS namespace (default: "fota_auth")
 *   DEVICE_AUTH_REAUTH_MARGIN — seconds before expiry to trigger re-auth (default: 86400 = 1 day)
 */

#include "FotaConfig.h"

#include <Arduino.h>
#include <HTTPClient.h>
#include <Preferences.h>
#include <WiFiClientSecure.h>

// ─── Compile-time defaults ────────────────────────────────────────────────────

#ifndef DEVICE_AUTH_SERVER_URL
/** FOTA backend base URL. Override with the same value as FOTA_SERVER_URL. */
#define DEVICE_AUTH_SERVER_URL FOTA_SERVER_URL
#endif

#ifndef DEVICE_AUTH_DEVICE_ID
/** Device business-key identifier registered in the FOTA platform. */
#define DEVICE_AUTH_DEVICE_ID ""
#endif

#ifndef DEVICE_AUTH_DEVICE_SECRET
/** Raw 64-hex-char secret generated by POST /devices/:id/credentials. */
#define DEVICE_AUTH_DEVICE_SECRET ""
#endif

#ifndef DEVICE_AUTH_API_PREFIX
/** API path prefix matching the backend configuration. */
#define DEVICE_AUTH_API_PREFIX FOTA_API_PREFIX
#endif

#ifndef DEVICE_AUTH_NVS_NS
/** NVS (Preferences) namespace used to persist the cached JWT. */
#define DEVICE_AUTH_NVS_NS "fota_auth"
#endif

#ifndef DEVICE_AUTH_REAUTH_MARGIN
/**
 * Re-authenticate this many seconds before the token actually expires.
 * Default: 86400 (1 day). Set to 0 to re-authenticate only on expiry.
 */
#define DEVICE_AUTH_REAUTH_MARGIN 86400
#endif

// ─── Class ────────────────────────────────────────────────────────────────────

/**
 * @class DeviceAuth
 * @brief Manages device authentication, token persistence, and token refresh flow.
 */
class DeviceAuth {
public:
    /** @brief Construct a new DeviceAuth instance with compile-time defaults. */
    DeviceAuth();

    // ── Configuration ────────────────────────────────────────────────────────

    /**
     * @brief Set the FOTA backend base URL.
     * @param url NUL-terminated HTTPS base URL.
     * @return void
     */
    void setServerUrl(const char *url);

    /**
     * @brief Set the API path prefix used for authentication endpoints.
     * @param prefix NUL-terminated API prefix string (for example "/api/v1").
     * @return void
     */
    void setApiPrefix(const char *prefix);

    /**
     * @brief Set the device business-key identifier.
     * Must match the device_id registered in the FOTA platform dashboard.
     * Override compile-time DEVICE_AUTH_DEVICE_ID.
     * @param deviceId NUL-terminated device identifier from the dashboard.
     * @return void
     */
    void setDeviceId(const char *deviceId);

    /**
     * @brief Set the raw 64-hex-char device secret.
     * Generated by POST /devices/:id/credentials in the FOTA platform.
     * Override compile-time DEVICE_AUTH_DEVICE_SECRET.
     * @param secret NUL-terminated device secret.
     * @return void
     */
    void setDeviceSecret(const char *secret);

    /**
     * @brief Set the root CA certificate (PEM) for TLS verification.
     * Use the same cert as FotaClient::setCACert().
     * Pass nullptr to skip TLS verification (insecure; development only).
     * @param pem NUL-terminated PEM CA certificate or nullptr.
     * @return void
     */
    void setCACert(const char *pem);

    // ── Core API ─────────────────────────────────────────────────────────────

    /**
     * @brief Ensure the cached device JWT is valid.
     *
     * Steps:
     *   1. Try to load a previously-saved token from NVS.
     *   2. If no token or token expires within DEVICE_AUTH_REAUTH_MARGIN seconds,
     *      call authenticate() to obtain a fresh JWT.
     *   3. Save the new token to NVS.
     *
     * Call this in setup() after WiFi is connected, before fota.begin().
     * @note Emits info/debug logs for token source selection and validation path.
     *
     * @return true if a valid token is now available; false on authentication failure.
     */
    bool ensureValid();

    /**
     * @brief Force a new authentication request against the FOTA backend.
     *
     * Calls POST /api/v1/devices/authenticate with device_id + device_secret.
     * On success, stores the JWT in NVS and caches it in memory.
     * @note Emits debug logs for HTTP response codes and error logs on failures.
     *
     * @return true on success; false if the request failed (see lastError()).
     */
    bool authenticate();

    /**
     * @brief Apply the cached token to a FotaClient instance.
     *
     * Equivalent to: fota.setAuthToken(auth.getToken()).
     * Call ensureValid() before this to guarantee a valid token.
     *
     * @tparam FotaClientT  FotaClient class (template avoids circular include).
     * @param fota Reference to a configured FotaClient-like instance.
     * @return void
     */
    template <typename FotaClientT>
    void applyTo(FotaClientT &fota) {
        if (_token[0] != '\0') {
            fota.setAuthToken(_token);
        }
    }

    // ── Token accessors ───────────────────────────────────────────────────────

    /**
     * @brief Return the cached JWT token.
     * @return Pointer to internal NUL-terminated token buffer.
     */
    const char *getToken() const { return _token; }

    /**
     * @brief Return whether the cached token is currently usable.
     *
     * Returns true if the cached token is non-empty AND has not yet expired
     * (accounting for DEVICE_AUTH_REAUTH_MARGIN).
     *
     * Requires the device clock to be set (NTP). If time() returns 0 or a
     * value before 2020-01-01, the expiry check is skipped and the token is
     * assumed valid.
     * @return true when token exists and is still valid.
      */
    bool isTokenValid() const;

    /**
     * @brief Return Unix timestamp for token expiry.
     * @return Expiry timestamp in seconds since epoch, or 0 if unknown.
     */
    uint32_t getTokenExpiry() const { return _tokenExpiry; }

    // ── NVS persistence ───────────────────────────────────────────────────────

    /**
     * @brief Load a previously-saved token and expiry from NVS.
     * @return true if a token was found and loaded.
     */
    bool loadFromNVS();

    /**
     * @brief Save the current token and expiry to NVS.
     * @return void
     */
    void saveToNVS();

    /**
     * @brief Erase the cached token from NVS.
     * @return void
     */
    void clearNVS();

    /**
     * @brief Return the last internal error message.
     * @return Pointer to NUL-terminated internal error message buffer.
     */
    const char *lastError() const { return _lastError; }

private:
    char        _serverUrl[256];
    char        _apiPrefix[32];
    char        _deviceId[64];
    char        _deviceSecret[130]; // 64 hex chars + NUL + safety margin
    const char *_caCert;

    char     _token[2048]; // JWT typically ~800 bytes; 2 KiB is safe
    uint32_t _tokenExpiry; // Unix timestamp; 0 = unknown

    char _lastError[128];

    /** Parse the `exp` field from the cached JWT payload (base64url-decoded). */
    bool _parseExpiry();

    void _setError(const char *fmt, ...);
};
